# Generated by Django 2.2.6 on 2019-11-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_globalindexing'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopReviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200, verbose_name='Reviewer Designation')),
                ('reviewer_name', models.CharField(max_length=200, verbose_name='Reviewer Name')),
                ('reviewer_info', models.CharField(max_length=1000, verbose_name='Reviewer Info')),
                ('profile', models.ImageField(blank=True, null=True, upload_to='reviewers/')),
            ],
        ),
    ]
