# Generated by Django 2.2.6 on 2020-03-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_topreviewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Donator name')),
                ('d_amt', models.CharField(blank=True, max_length=300, null=True, verbose_name='Donater Amount(Only for record)')),
                ('d_picture', models.ImageField(blank=True, null=True, upload_to='Donator photo')),
            ],
        ),
    ]
