# Generated by Django 2.2.6 on 2020-03-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_donator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donator',
            name='d_picture',
            field=models.ImageField(blank=True, null=True, upload_to='Donator photo', verbose_name='Donator Photo'),
        ),
    ]
