# Generated by Django 2.2.12 on 2020-05-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20200328_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publish_date',
            new_name='join_date',
        ),
    ]
